### ISSUE TITLE
update to bitcoinj 0.11 final

### ISSUE THREAD

**Issue by mackuba** [hivewallet/BitcoinKit#22]
@nschum can you take a look later? It sounds simple but it's not ;) They've changed some dependencies in the pom's (slf4j) and it doesn't compile now, and our pom's are kind of a mess...

**Comment by jonasschnelli** [comment]
@nschum, you might look here: https://github.com/jonasschnelli/BitcoinJKit/blob/master/BitcoinJKit/java/pom.xml 
I've cleaned up the pom.xml, got rid of the linking of the bitcoinj "code" folder as well as of the two maven project structure. Sorry for not creating a pull request, but i'm currently busy with other stuff.

**Comment by mikehearn** [comment]
You need to upgrade to 0.11.2 when it comes out, otherwise users will start missing transactions that pay the new lower fee level. So far no wallets do that by default AFAIK but they will start soon. Sorry for the hassle.

**Comment by mackuba** [comment]
Oh, there's a new lower official fee? How much is it?

**Comment by mackuba** [comment]
Are you saying bitcoinj would reject transactions with a lower fee, even if they were accepted by other peers and/or miners? Shouldn't it be miners and full nodes' job to determine if a transaction is valid?

**Comment by mikehearn** [comment]
Relay fee dropped by 10x in Bitcoin Core 0.9 but we have to wait until most miners and nodes have upgraded before we can start actually levying the lower fee, otherwise tx reliability would go down. We'll bump bitcoinj at the right time and do a new point release so you'll get it automatically. Unfortunately versions older than 0.11.2 silently drop transactions that pay lower than the min fee, and then (oops) don't notice when they get confirmed either. So that's bad news. Required upgrade time!

**Comment by mikehearn** [comment]
Or rather, 0.11.2 does that too, but its idea of the min fee is different. It's a bug and yes I'm going to fix it. It's a bad interaction between the spam filtering that was put in, in response to the 1Sochi spam attacks, and Bloom filtering.

**Comment by mackuba** [comment]
Ah, ok, I see. Looks like I'll have to get my hands dirty with Maven this week...

**Comment by mikehearn** [comment]
Let me know if you need any assistance.

**Comment by nschum** [comment]
I have 0.11.2 running locally, just not through the submodule (see #16).
